"""
Packaging utilities
打包生成的项目
"""
import os
import shutil
import zipfile
from pathlib import Path
from typing import Optional
import logging

logger = logging.getLogger(__name__)


def create_docker_compose(project_dir: Path) -> Path:
    """
    创建docker-compose.yml文件

    Args:
        project_dir: 项目目录

    Returns:
        docker-compose.yml文件路径
    """
    docker_compose_content = """version: '3.8'

services:
  backend:
    build: ./backend
    ports:
      - "5000:5000"
    volumes:
      - ./backend:/app
    environment:
      - FLASK_APP=app.py
      - FLASK_ENV=development
    command: python app.py

  frontend:
    build: ./frontend
    ports:
      - "8000:8000"
    volumes:
      - ./frontend:/app
    depends_on:
      - backend
    command: python -m http.server 8000

volumes:
  backend_data:
"""

    compose_file = project_dir / "docker-compose.yml"
    with open(compose_file, 'w', encoding='utf-8') as f:
        f.write(docker_compose_content)

    logger.info(f"Created docker-compose.yml at {compose_file}")
    return compose_file


def create_backend_dockerfile(backend_dir: Path) -> Path:
    """创建后端Dockerfile"""
    dockerfile_content = """FROM python:3.9-slim

WORKDIR /app

COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

COPY . .

EXPOSE 5000

CMD ["python", "app.py"]
"""

    dockerfile = backend_dir / "Dockerfile"
    with open(dockerfile, 'w', encoding='utf-8') as f:
        f.write(dockerfile_content)

    logger.info(f"Created Dockerfile at {dockerfile}")
    return dockerfile


def create_frontend_dockerfile(frontend_dir: Path) -> Path:
    """创建前端Dockerfile"""
    dockerfile_content = """FROM python:3.9-slim

WORKDIR /app

COPY . .

EXPOSE 8000

CMD ["python", "-m", "http.server", "8000"]
"""

    dockerfile = frontend_dir / "Dockerfile"
    with open(dockerfile, 'w', encoding='utf-8') as f:
        f.write(dockerfile_content)

    logger.info(f"Created Dockerfile at {dockerfile}")
    return dockerfile


def create_project_readme(project_dir: Path, requirement: str) -> Path:
    """
    创建项目README

    Args:
        project_dir: 项目目录
        requirement: 用户需求

    Returns:
        README文件路径
    """
    readme_content = f"""# Generated Application

**Auto-generated by DevSwarm Multi-Agent System**

## Original Requirement

{requirement}

## Project Structure

```
.
├── backend/          # Backend API (Flask)
├── frontend/         # Frontend UI (HTML/JS)
├── tests/            # Test files
├── docker-compose.yml
└── README.md
```

## Quick Start

### Option 1: Using Docker Compose (Recommended)

```bash
docker-compose up
```

Then open:
- Frontend: http://localhost:8000
- Backend API: http://localhost:5000

### Option 2: Manual Setup

#### Backend

```bash
cd backend
pip install -r requirements.txt
python app.py
```

Backend will run on http://localhost:5000

#### Frontend

```bash
cd frontend
python3 -m http.server 8000
```

Frontend will run on http://localhost:8000

## API Documentation

See `api_contract.json` for the complete API specification.

## Testing

Tests were automatically generated and run by the QA Agent during development.

## Generated By

DevSwarm Multi-Agent System - A collaborative AI development platform.

Components:
- **PM Agent**: Project planning and coordination
- **Backend Agent**: API implementation
- **Frontend Agent**: UI development
- **QA Agent**: Testing and quality assurance
"""

    readme_file = project_dir / "README.md"
    with open(readme_file, 'w', encoding='utf-8') as f:
        f.write(readme_content)

    logger.info(f"Created README.md at {readme_file}")
    return readme_file


def package_project(project_dir: Path, output_dir: Optional[Path] = None) -> Path:
    """
    打包项目为zip文件

    Args:
        project_dir: 项目目录
        output_dir: 输出目录（可选）

    Returns:
        zip文件路径
    """
    if output_dir is None:
        output_dir = project_dir.parent

    output_dir = Path(output_dir)
    output_dir.mkdir(parents=True, exist_ok=True)

    zip_filename = f"{project_dir.name}.zip"
    zip_path = output_dir / zip_filename

    logger.info(f"Packaging project to {zip_path}")

    with zipfile.ZipFile(zip_path, 'w', zipfile.ZIP_DEFLATED) as zipf:
        for root, dirs, files in os.walk(project_dir):
            # 排除某些目录
            dirs[:] = [d for d in dirs if d not in ['__pycache__', 'venv', '.git']]

            for file in files:
                file_path = Path(root) / file
                arcname = file_path.relative_to(project_dir.parent)
                zipf.write(file_path, arcname)

    logger.info(f"Project packaged successfully: {zip_path}")
    return zip_path


def finalize_project(project_id: str, workspace_root: str, requirement: str) -> Dict[str, Any]:
    """
    完成项目打包

    Args:
        project_id: 项目ID
        workspace_root: 工作区根目录
        requirement: 用户需求

    Returns:
        打包结果
    """
    project_dir = Path(workspace_root) / project_id
    backend_dir = project_dir / "backend"
    frontend_dir = project_dir / "frontend"

    # 创建Docker文件
    create_docker_compose(project_dir)
    create_backend_dockerfile(backend_dir)
    create_frontend_dockerfile(frontend_dir)

    # 创建项目README
    create_project_readme(project_dir, requirement)

    # 打包项目
    zip_path = package_project(project_dir)

    return {
        "project_dir": str(project_dir),
        "zip_file": str(zip_path),
        "files": [
            "docker-compose.yml",
            "README.md",
            "backend/Dockerfile",
            "frontend/Dockerfile"
        ]
    }
